### ISSUE TITLE
Add ESLint and/or JSCS

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/dash-elements#1]
I figure with enough folks working on this we'll quickly hit a point where there are code style conflicts. Would be nice to add these in early to validate any incoming PRs.

**Comment by surma** [comment]
Agreed. Will take a look at integrating that.

Any objections against just using [google/eslint-config-google](https://github.com/google/eslint-config-google) (for now)?

**Comment by robdodson** [comment]
sgtm
