### ISSUE TITLE
Should demo code be formatted the same as the implementation?

### ISSUE THREAD

**Issue by surma** [GoogleChrome/dash-elements#10]
Looking at [the demo code in @notwaldorf’s PR](https://github.com/GoogleChrome/dash-elements/pull/7/files#diff-6bcff783bbed0481cddd9105593178cc) I feel like it’s probably good to comment the CSS, too. Should we format the code in the same 2-column format as the implementation?

The parser isn’t currently able to (I think), but can be adjusted.

@notwaldorf @robdodson WDYT?

**Comment by robdodson** [comment]
Yeah let's do it.

**Comment by surma** [comment]
[Live demo](https://dash-elements.surma.link/fd1a0f8382e541133135ecefe3e5ca385b604bd4/dash-tab-panel.html)

**Comment by robdodson** [comment]
nice!
