### ISSUE TITLE
Remove empty spaces in responsive mode

### ISSUE THREAD

**Issue by surma** [GoogleChrome/dash-elements#11]
<img width="591" alt="screenshot 2017-01-25 16 33 40" src="https://cloud.githubusercontent.com/assets/234957/22299475/1c3800be-e31c-11e6-94f3-38ce028f0f6e.png">

**Comment by robdodson** [comment]
I see something similar in desktop mode.

<img width="1214" alt="screen shot 2017-01-25 at 8 38 44 am" src="https://cloud.githubusercontent.com/assets/1066253/22299632/bb78bb52-e2d9-11e6-81f9-84129898c4fa.png">

**Comment by surma** [comment]
That was intentional because I wanted JSDoc-like comments to only refer to the line of the method declaration.

<img width="1149" alt="screenshot 2017-01-25 16 44 34" src="https://cloud.githubusercontent.com/assets/234957/22299874/9f94f6c8-e31d-11e6-98dc-680569695c4a.png">

I can change that if desired.

**Comment by robdodson** [comment]
It's a little weird because I only have 1 comment, a big block comment at the top. It would make more sense if I had inline `//` comments but as it stands it looks like a bug to me. At least if there's no inline comments.

**Comment by robdodson** [comment]
If it's hard to change I could switch to using more inline comments. That might be better anyway.

**Comment by surma** [comment]
>  At least if there's no inline comments.

I might add that behavior.

But yes, I think more inline-comments would be ace.
