### ISSUE TITLE
[Q] Why skip keyboard processing on alt-key?

### ISSUE THREAD

**Issue by surma** [GoogleChrome/dash-elements#19]
Making issue because @robdodson looped in @alice:

Looking at the JS implementation of [OAA’s tab panel](http://oaa-accessibility.org/example/34/) they are skipping their keyboard processing code when the alt key is pressed. Any idea why that is? 

```JS
tabpanel.prototype.handleTabKeyPress = function($tab, e) { 
  if (e.altKey) { 
    // do nothing 
    return true; 
  } 

  switch (e.keyCode) { 
  // ...
  }
}
```

**Comment by alice** [comment]
Makes sense - if someone is using the Alt key they're probably using a keyboard shortcut for something else. e.g. JAWS uses Alt+up/down arrow to read previous/next sentence.

**Comment by notwaldorf** [comment]
Aren't they just looking for tabs? `alt`+`tab` is p useless inside a web page, if that's the case.

**Comment by surma** [comment]
Thanks @alice. 

@notwaldorf @robdodson I suggest we add this to all elements then. I’ll just go ahead and add that code piece to your elements. 

Q: Should we duplicate the comment/explanation across all elements or handle it like the CE and add a general explanation to the general intro?

**Comment by robdodson** [comment]
@notwaldorf I think they named their handler poorly. It's a general `onKeyDown` handler. And yeah, if someone hits `alt-down arrow` or something, we'd want to let the modifier do its thing. +1 for adding it to the elements.

We could say something like "Allow modifier shortcuts" with a link to a longer explanation in the general intro

**Comment by surma** [comment]
Sold! 🔨

**Comment by notwaldorf** [comment]
When you say "add it to all the elements" do you mean just the tab panel? Why would the tooltip need any key handlers? :/

**Comment by surma** [comment]
@notwaldorf I meant the more nuanced version of course. I meant “add it to all the elements where necessary”. oops 🙄
