### ISSUE TITLE
[tab-panel] Rename to dash-tabpanel

### ISSUE THREAD

**Issue by surma** [GoogleChrome/dash-elements#9]

**Comment by robdodson** [comment]
Fixed https://github.com/GoogleChrome/dash-elements/commit/23b43ebae1bf92334240130c20399808bd9fc8dd

**Comment by surma** [comment]
\<bikeshed\>Should I go for “tabpanel” rather than “tab-panel” for consistency with “radiogroup”\</bikeshed\>

**Comment by robdodson** [comment]
oh good question... I guess I prefer `<dash-tab-panel>` because it's a bit easier to read. I think I did `<dash-radio-group>`.

**Comment by surma** [comment]
I blame jetlag. Multiple dashes work just as fine. Closing
